// Code generated by coz. DO NOT EDIT.
/**
 * Chat UI of the-components
 * @module the-chat
 * @version 2.0.18
 */
'use strict'

import TheChat from './TheChat'
import TheChatForm from './TheChatForm'
import TheChatStyle from './TheChatStyle'
import TheChatTimeLine from './TheChatTimeLine'
import TheChatTimeLineItem from './TheChatTimeLineItem'

export default TheChat

export {
  TheChat,
  TheChatForm,
  TheChatStyle,
  TheChatTimeLine,
  TheChatTimeLineItem
}
